plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '7.1.2'
}

group = 'plus.tcord'
version = '1.0'


repositories {
    mavenCentral()
}

jar{
    manifest {
        attributes(
                'Main-Class': 'plus.tcord.TCordMain'
        )
    }
}

shadowJar{
    archiveFileName = 'TCord.jar'

}

dependencies {
    implementation 'com.google.code.gson:gson:2.13.1'
}